### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
#dependencies
import pandas as pd
import numpy as np

#load file
file = "Resources/purchase_data.csv"

#read file, store in df
df_purchase = pd.read_csv(file)

df_purchase.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

In [3]:
#obtain true count (no duplicates) with length of unique
player_num = len(df_purchase['SN'].unique())

df_player_count = pd.DataFrame({"Total Players" : [player_num]})
df_player_count

   Total Players
0            576

* Display the total number of players

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [15]:
#obtain values for unique items, average price, number of purchases, total revenue
unique_items = len(df_purchase['Item ID'].unique())
average_price = df_purchase['Price'].mean()
total_purchases = df_purchase['Price'].count()
total_revenue = df_purchase['Price'].sum()

#construct df
df_purch_analysis = pd.DataFrame({'Unique Items' : [unique_items],
                                 'Average Price' : [average_price],
                                 'Total no. of Purchases' : [total_purchases],
                                 'Total Revenue' : [total_revenue]
                                 })

#format values
df_purch_analysis['Average Price'] = df_purch_analysis['Average Price'].map("${:,.2f}".format)
df_purch_analysis['Total Revenue'] = df_purch_analysis['Total Revenue'].map("${:,.2f}".format)

#display df
df_purch_analysis

   Unique Items Average Price  Total no. of Purchases Total Revenue
0           183         $3.05                     780     $2,379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [5]:
#count unique players
unique_players = len(df_purchase['SN'].unique())

#new df w/ gender
df_gender = df_purchase.rename(columns={'SN':'Players'}) \
                       .loc[:, ['Players', 'Gender']] \
                       .drop_duplicates(subset='Players')

#obtain counts
male_count = len(df_gender.loc[df_gender['Gender'] == 'Male', ["Players"]])
female_count = len(df_gender.loc[df_gender['Gender'] == 'Female', ["Players"]])
z_count = len(df_gender.loc[df_gender['Gender'] == 'Other / Non-Disclosed', ["Players"]])

#determine percentages
male_pct = round(male_count/unique_players * 100, 2)
female_pct = round(female_count/unique_players *100, 2)
z_pct = round(z_count/unique_players *100, 2)

#gender summary df
df_gensum = pd.DataFrame({
        'Total Count' : [z_count, female_count, male_count],
        'Percentage' : [z_pct, female_pct, male_pct],
        'Gender' : ["Non-Binary/Undisclosed", "Female", "Male"]
})

#set index/remove extra row
df_gensum.set_index('Gender', drop=True, inplace=True)
df_gensum.index.name=None
df_gensum

                        Total Count  Percentage
Non-Binary/Undisclosed           11        1.91
Female                           81       14.06
Male                            484       84.03


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [6]:
#calc purchase counts
purchase_ct = len(df_purchase['Purchase ID'])
purch_m = len(df_purchase.loc[df_purchase['Gender'] == 'Male'])
purch_f = len(df_purchase.loc[df_purchase['Gender'] == 'Female'])
purch_z = len(df_purchase.loc[df_purchase['Gender'] == 'Other / Non-Disclosed'])

#calc sums
sum = df_purchase['Price'].sum()
sum_m = df_purchase.loc[df_purchase['Gender'] == 'Male', 'Price'].sum()
sum_f = df_purchase.loc[df_purchase['Gender'] == 'Female', 'Price'].sum()
sum_z = df_purchase.loc[df_purchase['Gender'] == 'Other / Non-Disclosed', 'Price'].sum()

#calc total averages
avg_m = df_purchase.loc[df_purchase['Gender'] == 'Male', 'Price'].mean()
avg_f = df_purchase.loc[df_purchase['Gender'] == 'Female', 'Price'].mean()
avg_z = df_purchase.loc[df_purchase['Gender'] == 'Other / Non-Disclosed', 'Price'].mean()

#calc player averages (loc for each gender, group by name, sum/mean)
newdf = df_purchase.loc[:, ['SN', 'Gender', 'Price']]
um = newdf.loc[newdf['Gender']=='Male',['SN','Price']]
uf = newdf.loc[newdf['Gender']=='Female',['SN','Price','Gender']]
uz = newdf.loc[newdf['Gender']=='Other / Non-Disclosed', ['SN','Price','Gender']]

sngroupm = um.groupby('SN')
sngroupf = uf.groupby('SN')
sngroupz = uz.groupby('SN')

pavgm = sngroupm['Price'].agg('sum').mean()
pavgf = sngroupf['Price'].agg('sum').mean()
pavgz = sngroupz['Price'].agg('sum').mean()


#summary dataframe, set index to Gender
df_genpurch = pd.DataFrame ({
        'Gender' : ['Non-Binary/Undisclosed', 'Female', 'Male'],
        'Purchase Count' : [purch_z, purch_f, purch_m],
        'Total Purchase Amount' : [sum_z, sum_f, sum_m],
        'Average Purchase Price' : [avg_z, avg_f, avg_m],
        'Average Purchase per User' :[pavgz, pavgf, pavgm]
    })


#formatting w/ loop
genpurch_format = {'Total Purchase Amount': '${:,.2f}',\
                   'Average Purchase Price': '${:,.2f}',\
                    'Average Purchase per User': '${:,.2f}'}


for key, value in genpurch_format.items():
    df_genpurch[key] = df_genpurch[key].apply(value.format)

#format by col    
#df_genpurch['Total Purchase Amount'] = money(df_genpurch['Total Purchase Amount'].map('${:,.2f}'.format)
#df_genpurch['Average Purchase Price'] = df_genpurch['Average Purchase Price'].map('${:,.2f}'.format)
#df_genpurch['Average Purchase per User'] = df_genpurch['Average Purchase per User'].map('${:,.2f}'.format)

#set index/remove name
df_genpurch.set_index('Gender', drop=True, inplace=True)
df_genpurch.index.name=None

#display
df_genpurch

,Purchase Count,Total Purchase Amount,Average Purchase Price,Average Purchase per User
Non-Binary/Undisclosed,15,$50.19,$3.35,$4.56
Female,113,$361.94,$3.20,$4.47
Male,652,"$1,967.64",$3.02,$4.07

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [16]:
#new df for age
df_age = df_purchase.rename(columns={'SN':'Players'}) \
                       .loc[:, ['Players', 'Age', 'Price']] \
                       .drop_duplicates(subset='Players')

#create bins/labels
bins = [0, 9, 14, 19, 24, 29, 34, 39, 999]
bin_labels = ['Under 10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40 and Over' ]
bins = pd.cut(df_age['Age'], bins, labels=bin_labels)

#construct dataframe, perform calculations
df_sumage = df_age.groupby(bins)['Age'].agg(['count'])
df_sumage = df_sumage.rename(columns={'count':'Total Count'})

#format
df_sumage['Percentage'] = ((df_sumage['Total Count'] / player_num) * 100).map('{:,.2f}%'.format)
df_sumage.index.name=None

#display
df_sumage

             Total Count Percentage
Under 10              17      2.95%
10-14                 22      3.82%
15-19                107     18.58%
20-24                258     44.79%
25-29                 77     13.37%
30-34                 52      9.03%
35-39                 31      5.38%
40 and Over           12      2.08%

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [8]:
#df for total player and unique players
df_ageprice = df_purchase.rename(columns={'SN':'Players'})\
                        .loc[:, ['Players', 'Age', 'Price']]

df_agepriceU = df_purchase.rename(columns={'SN':'Players'})\
                        .loc[:, ['Players', 'Age', 'Price']]\
                        .drop_duplicates(subset='Players')

#create bins/labels
bins = [0, 9, 14, 19, 24, 29, 34, 39, 999]
bin_labels = ['Under 10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40 and Over']

#slice for total and total unique players
sliceage = pd.cut(df_ageprice['Age'], bins, labels=bin_labels)
binsU = pd.cut(df_agepriceU['Age'], bins, labels=bin_labels)

#construct dataframe for each, aggregate, perform calculations
df_sumage = df_ageprice.groupby(sliceage)['Age', 'Price']\
                        .agg({'Age':'count','Price':'sum'})\
                        .rename(columns={'Age':'Player Count', 'Price':'Total Sales'})

df_sumageU = df_agepriceU.groupby(binsU)['Age', 'Price']\
                        .agg({'Age':'count','Price':'sum'})\
                        .rename(columns={'Age':'Player Count', 'Price':'Total Sales'})

df_sumage['Average Purchase'] = (df_sumage['Total Sales'])/(df_sumage['Player Count'])
df_sumage['Average Total per Person'] = df_sumage['Total Sales']/(df_sumageU['Player Count'])

#formatting, remove index name
df_sumage['Total Sales'] = df_sumage['Total Sales'].map('${:,.2f}'.format)
df_sumage['Average Purchase'] = df_sumage['Average Purchase'].map('${:,.2f}'.format)
df_sumage['Average Total per Person'] = df_sumage['Average Total per Person'].map('${:,.2f}'.format)
df_sumage.index.name=None

#display
df_sumage

,Player Count,Total Sales,Average Purchase,Average Total per Person
Under 10,23,$77.13,$3.35,$4.54
10-14,28,$82.78,$2.96,$3.76
15-19,136,$412.89,$3.04,$3.86
20-24,365,"$1,114.06",$3.05,$4.32
25-29,101,$293.00,$2.90,$3.81
30-34,73,$214.00,$2.93,$4.12
35-39,41,$147.67,$3.60,$4.76
40 and Over,13,$38.24,$2.94,$3.19

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [9]:
#groupby, aggregate
df_spenders = df_purchase.groupby('SN')['SN', 'Price'].agg({'SN':'count', 'Price':'sum'})


df_spenders = df_spenders.rename(columns={'SN' : 'Purchases', 'Price' : 'Total Price'})
df_spenders['Average Purchase'] = df_spenders['Total Price'] / df_spenders['Purchases']


df_spenders.sort_values(by=['Total Price'], ascending=False, inplace=True)

#formatting/rearrange cols
df_spenders['Total Price'] = df_spenders['Total Price'].map('${:,.2f}'.format)
df_spenders['Average Purchase'] = df_spenders['Average Purchase'].map('${:,.2f}'.format)
df_spenders = df_spenders[['Purchases','Average Purchase','Total Price']]
df_spenders.index.name = None

#display
df_spenders.head(10)

              Purchases Average Purchase Total Price
Lisosia93             5            $3.79      $18.96
Idastidru52           4            $3.86      $15.45
Chamjask73            3            $4.61      $13.83
Iral74                4            $3.40      $13.62
Iskadarya95           3            $4.37      $13.10
Ilarin91              3            $4.23      $12.70
Ialallo29             3            $3.95      $11.84
Tyidaim51             3            $3.94      $11.83
Lassilsala30          3            $3.84      $11.51
Chadolyla44           3            $3.82      $11.46

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [10]:
#group by item name/id, aggregate
df_items = df_purchase.groupby(['Item ID','Item Name'])['Item Name','Price'].agg({'Item Name': 'count', 'Price':'sum'})

#rename/calculate avg price per item
df_items = df_items.rename(columns={'Item Name' : 'Purchase Count'})
df_items['Average'] = df_items['Price']/df_items['Purchase Count']

#formatting
df_items['Price'] = df_items['Price'].map('${:,.2f}'.format)
df_items['Average'] = df_items['Average'].map('${:,.2f}'.format)

#sort by purchase count
df_items.sort_values(by=['Purchase Count'], ascending=False, inplace=True)

#display
df_items

,,Purchase Count,Price,Average
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$50.76,$4.23
145,Fiery Glass Crusader,9,$41.22,$4.58
108,"Extraction, Quickblade Of Trembling Hands",9,$31.77,$3.53
82,Nirvana,9,$44.10,$4.90
19,"Pursuit, Cudgel of Necromancy",8,$8.16,$1.02
103,Singed Scalpel,8,$34.80,$4.35
75,Brutality Ivory Warmace,8,$19.36,$2.42
72,Winter's Bite,8,$30.16,$3.77
60,Wolf,8,$28.32,$3.54
59,"Lightning, Etcher of the King",8,$33.84,$4.23
37,"Shadow Strike, Glory of Ending Hope",8,$25.28,$3.16
34,Retribution Axe,8,$17.76,$2.22
92,Final Critic,8,$39.04,$4.88
53,Vengeance Cleaver,7,$14.35,$2.05
110,Suspension,7,$10.08,$1.44
7,"Thorn, Satchel of Dark Souls",7,$9.31,$1.33
71,Demise,7,$11.27,$1.61
117,"Heartstriker, Legacy of the Light",7,$12.53,$1.79
159,"Oathbreaker, Spellblade of Trials",7,$21.56,$3.08
85,Malificent Bag,7,$12.25,$1.75
164,Exiled Doomblade,7,$11.41,$1.63
141,Persuasion,7,$22.33,$3.19
78,"Glimmer, Ender of the Moon",7,$30.80,$4.40
102,Avenger,6,$20.64,$3.44
129,"Fate, Vengeance of Eternal Justice",6,$9.24,$1.54
93,Apocalyptic Battlescythe,6,$11.82,$1.97
54,Eternal Cleaver,6,$15.00,$2.50
3,Phantomlight,6,$14.94,$2.49
2,Verdict,6,$14.88,$2.48
40,Second Chance,6,$15.12,$2.52
...,...,...,...,...
81,Dreamkiss,2,$7.22,$3.61
6,Rusty Skull,2,$7.40,$3.70
18,"Torchlight, Bond of Storms",2,$9.30,$4.65
26,Unholy Wand,2,$2.24,$1.12
28,"Flux, Destroyer of Due Diligence",2,$2.12,$1.06
30,Stormcaller,2,$4.42,$2.21
158,"Darkheart, Butcher of the Champion",2,$4.90,$2.45
69,"Frenzy, Defender of the Harvest",2,$3.96,$1.98
132,Persuasion,2,$6.66,$3.33
63,Stormfury Mace,2,$9.98,$4.99
56,Foul Titanium Battle Axe,2,$5.84,$2.92
127,"Heartseeker, Reaver of Souls",2,$7.84,$3.92
48,"Rage, Legacy of the Lone Victor",2,$4.96,$2.48
125,Whistling Mithril Warblade,2,$2.00,$1.00
43,Foul Edge,2,$7.08,$3.54
115,Spectral Diamond Doomblade,2,$4.08,$2.04
33,Curved Axe,2,$2.32,$1.16
31,Trickster,2,$3.10,$1.55
118,"Ghost Reaver, Longsword of Magic",1,$2.17,$2.17
47,"Alpha, Reach of Ending Hope",1,$3.58,$3.58
42,The Decapitator,1,$1.75,$1.75
27,"Riddle, Tribute of Ended Dreams",1,$3.30,$3.30
126,Exiled Mithril Longsword,1,$2.00,$2.00
51,Endbringer,1,$4.66,$4.66
90,Betrayer,1,$2.94,$2.94
104,Gladiator's Glaive,1,$1.93,$1.93
23,Crucifer,1,$1.99,$1.99
180,Stormcaller,1,$3.36,$3.36
91,Celeste,1,$4.17,$4.17
134,Undead Crusader,1,$4.50,$4.50

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [14]:
#recreate df 
df_profit = df_purchase.groupby(['Item ID','Item Name'])['Item Name','Price'].agg({'Item Name': 'count', 'Price':'sum'})

#rename/calculate avg and total price per item
df_profit = df_profit.rename(columns={'Item Name' : 'Purchase Count'})
df_profit['Average'] = df_profit['Price']/df_items['Purchase Count']
df_profit['Total Price'] = df_profit['Average'] * df_items['Purchase Count']

#formatting
df_profit['Price'] = df_profit['Price'].map('${:,.2f}'.format)
df_profit['Average'] = df_profit['Average'].map('${:,.2f}'.format)

#sort and drop price
df_profit.sort_values(by=['Total Price'], ascending=False, inplace=True)
df_profit.drop('Price', axis=1, inplace=True)
df_profit

,,Purchase Count,Average,Total Price
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,50.76
82,Nirvana,9,$4.90,44.10
145,Fiery Glass Crusader,9,$4.58,41.22
92,Final Critic,8,$4.88,39.04
103,Singed Scalpel,8,$4.35,34.80
59,"Lightning, Etcher of the King",8,$4.23,33.84
108,"Extraction, Quickblade Of Trembling Hands",9,$3.53,31.77
78,"Glimmer, Ender of the Moon",7,$4.40,30.80
72,Winter's Bite,8,$3.77,30.16
60,Wolf,8,$3.54,28.32
179,"Wolf, Promise of the Moonwalker",6,$4.48,26.88
160,Azurewrath,6,$4.40,26.40
25,Hero Cane,6,$4.35,26.10
37,"Shadow Strike, Glory of Ending Hope",8,$3.16,25.28
139,"Mercy, Katana of Dismay",5,$4.94,24.70
128,"Blazeguard, Reach of Eternity",5,$4.91,24.55
138,"Peacekeeper, Wit of Dark Magic",5,$4.74,23.70
141,Persuasion,7,$3.19,22.33
87,"Deluge, Edge of the West",5,$4.43,22.15
159,"Oathbreaker, Spellblade of Trials",7,$3.08,21.56
136,Ghastly Adamantite Protector,6,$3.58,21.48
65,Conqueror Adamantite Mace,5,$4.24,21.20
101,Final Critic,5,$4.19,20.95
102,Avenger,6,$3.44,20.64
133,Faith's Scimitar,5,$4.09,20.45
39,"Betrayal, Whisper of Grieving Widows",5,$3.94,19.70
111,Misery's End,4,$4.89,19.56
165,Bone Crushing Silver Skewer,4,$4.86,19.44
75,Brutality Ivory Warmace,8,$2.42,19.36
52,Hatred,4,$4.84,19.36
...,...,...,...,...
124,Venom Claymore,4,$1.29,5.16
0,Splinter,4,$1.28,5.12
155,War-Forged Gold Deflector,5,$1.01,5.05
48,"Rage, Legacy of the Lone Victor",2,$2.48,4.96
158,"Darkheart, Butcher of the Champion",2,$2.45,4.90
51,Endbringer,1,$4.66,4.66
134,Undead Crusader,1,$4.50,4.50
30,Stormcaller,2,$2.21,4.42
135,Warped Diamond Crusader,3,$1.40,4.20
91,Celeste,1,$4.17,4.17
177,"Winterthorn, Defender of Shifting Worlds",2,$2.08,4.16
70,Hope's End,4,$1.03,4.12
115,Spectral Diamond Doomblade,2,$2.04,4.08
69,"Frenzy, Defender of the Harvest",2,$1.98,3.96
47,"Alpha, Reach of Ending Hope",1,$3.58,3.58
180,Stormcaller,1,$3.36,3.36
27,"Riddle, Tribute of Ended Dreams",1,$3.30,3.30
183,Dragon's Greatsword,3,$1.09,3.27
31,Trickster,2,$1.55,3.10
168,"Sun Strike, Jaws of Twisted Visions",2,$1.48,2.96
90,Betrayer,1,$2.94,2.94
33,Curved Axe,2,$1.16,2.32
26,Unholy Wand,2,$1.12,2.24
118,"Ghost Reaver, Longsword of Magic",1,$2.17,2.17
28,"Flux, Destroyer of Due Diligence",2,$1.06,2.12
125,Whistling Mithril Warblade,2,$1.00,2.00
126,Exiled Mithril Longsword,1,$2.00,2.00
23,Crucifer,1,$1.99,1.99
104,Gladiator's Glaive,1,$1.93,1.93
42,The Decapitator,1,$1.75,1.75